#!/bin/bash

#SBATCH -N 1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH -A master        # Replace with the desired account name
#SBATCH -p normal        # Replace with the desired partition name
#SBATCH --output=R-%x.%j.out
#SBATCH --error=R-%x.%j.err


source venv/bin/activate                # activate venv

python3 ./tools/test.py --method SeqUDSearch --max-lgb-jobs 10 --n-repeats 3 --inner-n-folds 10 --inner-shuffle --inner-random-state 9 --dataset accel 
