#!/bin/bash

#SBATCH --ntasks=1   ## Number of tasks that will be allocated
#SBATCH --nodes=1   ## Number of nodes that will be allocated
#SBATCH --cpus-per-task=1   ## Number of CPUs allocated for each tas

#SBATCH -A master              # Replace with the desired account name
#SBATCH -p normal               # Replace with the desired partition name
#SBATCH --output=job-result.out


#SBATCH -t 10-00:00:0                     # Set a time limit for the job (e.g., 10 minutes)
#SBATCH --mem-per-cpu=4G              # Request memory per CPU (e.g., 4GB)

# module load cuda                      # Example: Load CUDA module
source venv/bin/activate                # activate venv

# Commands to run your GPU job
python3 ./tools/search.py